"""Add granted_fields for granular consent

Revision ID: 6178b285247f
Revises: 78ceda5d7fda
Create Date: 2025-10-18 09:43:14.979553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6178b285247f'
down_revision = '78ceda5d7fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth2_authorization_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('granted_fields', sa.JSON(), nullable=True))

    with op.batch_alter_table('oauth2_client', schema=None) as batch_op:
        batch_op.alter_column('client_secret',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('oauth2_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('granted_fields', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth2_token', schema=None) as batch_op:
        batch_op.drop_column('granted_fields')

    with op.batch_alter_table('oauth2_client', schema=None) as batch_op:
        batch_op.alter_column('client_secret',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('oauth2_authorization_code', schema=None) as batch_op:
        batch_op.drop_column('granted_fields')

    # ### end Alembic commands ###
